# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - inclusive_language
  - switch_case_alignment
  - identifier_name
  - multiple_closures_with_trailing_closure
  - for_where
excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - .build

opt_in_rules:
  - force_cast
  - force_try
  - force_unwrapping

force_cast:
  severity: error
force_try:
  severity: error
force_unwrapping:
  severity: error

line_length:
  ignores_comments: true

nesting:
  type_level: 4
